<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
require APPPATH . '/libraries/REST_Controller.php';


/**
 * This is an example of a few basic user interaction methods you could use
 * all done with a hardcoded array
 *
 * @package         CodeIgniter
 * @subpackage      Rest Server
 * @category        Controller
 * @author          Phil Sturgeon, Chris Kacerguis
 * @license         MIT
 * @link            https://github.com/chriskacerguis/codeigniter-restserver
 */
class Bkk extends REST_Controller {
    function __construct($config = 'rest') {
        parent::__construct($config);
        //$this->load->librari(array('database'));
    }
    public function lowongan_get(){
    $query = $this->db->get('d_lowongan');
    $result = $query->result_array();
    $jns_kelamin    = $this->get('jns_kelamin');
    $umur           = $this->get('umur');
    $id             = $this->get('id');
    if($umur === NULL AND $jns_kelamin === NULL AND $id === NULL){
         if($result){
    
        $this->response($result,200);
        //echo var_dump($data);
        }else{
            $this->response([
                    'status' => FALSE,
                    'message' => 'Error'
                ], REST_Controller::HTTP_NOT_FOUND); 
        }
    }else{
            if($jns_kelamin !== NULL){
                $this->db->where(array('jns_kelamin'=>$jns_kelamin));
                $q = $this->db->get('d_lowongan');
                $hsl = $q->result_array();
                $this->response($hsl,200);
                
            }elseif ($umur !== NULL) {
                $this->db->where('max_umur <=',$umur);
                $q = $this->db->get('d_lowongan');
                $hsl = $q->result_array();
                $this->response($hsl,200);
                
            }elseif(!empty($id)){
                $this->db->where('id_lowongan',$id);
                $q = $this->db->get('d_lowongan');
                $hsl = $q->result_array();
                $this->response($hsl,200);
            }
            else{
                $this->response([
                    'status' => FALSE,
                    'message' => 'Error'
                ], REST_Controller::HTTP_NOT_FOUND); 
            }
        }
    }
    public function saldo_get(){
        $id = $this->get('id');
        $this->db->where('user_id',$id);
        $q = $this->db->get('d_saldo');    
        $hsl = $q->result_array();
        if(!empty($id)){
        
            $this->response($hsl,200);
        }else{
            $this->response([
                    'status' => FALSE,
                    'message' => 'Error'
                ], 200); 
        }
    }
    
    function login_post(){
        $data = (array)  json_decode(file_get_contents('php://input'));
       
        $usr = $data['username'];
        $psw = md5($data['password']);
        
        $q = $this->db->query("SELECT * FROM d_user where username = '$usr' AND password = '$psw'");
        if($q->num_rows() == 1){
            $message = [
            'user_id' => $q->row()->user_id, // Automatically generated by the model
            'message' => 'Login Berhasil'
        ];
            $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
        }else{
            $this->response([
                    'status' => FALSE,
                    'message' => 'Error'
                ], 200); 
        }
    }
    
    function alogin_get(){
        $data = (array)  json_decode(file_get_contents('php://input'));
       
        $usr = $this->get('usr');
        $ps = $this->get('psw');
        $psw = md5($ps);
        
        $q = $this->db->query("SELECT * FROM d_user where username = '$usr' AND password = '$psw'");
        if($q->num_rows() == 1){
            $message = [
            'user_id' => $q->row()->user_id, // Automatically generated by the model
            'message' => 'Login Berhasil'
        ];
            $this->set_response($message, REST_Controller::HTTP_CREATED); // CREATED (201) being the HTTP response code
        }else{
            $this->response([
                    'status' => FALSE,
                    'message' => 'Error'
                ], 200); 
        }
    }
    
    function apply_post(){
        $id_lowongan    = $this->post('id');
        $user_id        = $this->post('user_id');
        
        $q = $this->db->query("SELECT * FROM d_apply WHERE id_lowongan = '$id_lowongan' AND user_id = '$user_id'");
        if($q->num_rows > 0){
            $this->set_response(
                        [
                            'status' => FALSE,
                            'pesan'=> 'Gagal'
                        ],REST_Controller::HTTP_CREATED
                    );
        }else{
            //proses
            $this->set_response(
                        [
                            'status' => TRUE,
                            'pesan'=> 'Berhasil apply lowongan'
                        ],REST_Controller::HTTP_CREATED
                    );
        }
                  
    }
}